# File: backend.yml

services:
  backend-dev:
    image: ${BACKEND_DEV_IMAGE}
    container_name: backend-dev
    restart: always
    env_file: .env
    environment:
      - PORT=4000
    networks:
      - dev_network  
    ports:
      - "4000:4000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
