# File: lms-devops/docker-compose.dev.yml

version: '3.8'

services:
  backend-dev:
    image: ${BACKEND_DEV_IMAGE}
    container_name: backend-dev
    restart: always
    env_file: .env
    expose:
      - "4000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend-dev:
    image: ${FRONTEND_DEV_IMAGE}
    container_name: frontend-dev
    restart: always
    ports:
      - "6000:3000"
      - "6001:3001"
      - "6002:3002"
      - "6003:3003"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend-dev:4000
    depends_on:
      backend-dev:
        condition: service_healthy
