# File: lms-devops/docker-compose.dev.yml

version: '3.8'

services:
  backend-dev:
    # Use a standard environment variable for the image
    image: ${BACKEND_DEV_IMAGE}
    container_name: backend-dev
    restart: always
    # Tell the container to load its runtime variables from an .env file
    env_file: .env
    expose:
      - "4000"

  frontend-dev:
    # You should do the same for the frontend image
    image: ${FRONTEND_DEV_IMAGE}
    container_name: frontend-dev
    restart: always
    ports:
      - "6000:3000"
      - "6001:3001"
      - "6002:3002"
      - "6003:3003"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend-dev:4000
    depends_on:
      - backend-dev
