version: '3.8'

services:
  backend-dev:
    image: ghcr.io/${{ secrets.GITHUB_REPOSITORY_OWNER }}/lms-core:dev
    container_name: backend-dev
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL_DEV}
      # Add other dev-specific environment variables here
      - PORT=4000
    expose:
      - "4000" # Expose port only to other containers in the network

  frontend-dev:
    image: ghcr.io/${{ secrets.GITHUB_REPOSITORY_OWNER }}/lms-monorepo:dev
    container_name: frontend-dev
    restart: always
    ports:
      # Map all 4 frontend apps to ports on the host
      - "9000:3000"
      - "9001:3001"
      - "9002:3002"
      - "9003:3003"
    environment:
      # The frontend can talk to the backend using its service name
      - NEXT_PUBLIC_API_URL=http://backend-dev:4000
    depends_on:
      - backend-dev