# This file only defines the frontend service
services:
  frontend-dev:
    image: ${FRONTEND_DEV_IMAGE} # The image built locally on the server
    container_name: frontend-dev
    restart: always
    ports:
      - "7000:3000"
      - "7001:3001"
      - "7002:3002"
      - "7003:3003"
    networks:
      - dev_network
    environment:
      - NEXT_PUBLIC_API_URL=http://backend-dev:4000/api
    depends_on:
      backend-dev:
        condition: service_healthy
